### ISSUE TITLE
Using key for table rows

### ISSUE THREAD

**Issue by aandrey1993** [Daimon31999/maib-task#10]
В компоненте `DashboardTable`, использование даты в качестве уникального ключа при формировании строк таблицы, не самая хорошая идея, так как даты в Ваших тестовых данных  повторяются:

![изображение](https://user-images.githubusercontent.com/49781313/99115286-da553100-25fa-11eb-8041-0d2782b5f476.png)
![изображение](https://user-images.githubusercontent.com/49781313/99115371-f527a580-25fa-11eb-9adc-6ce74a717ffa.png)

Консоль браузера:
![изображение](https://user-images.githubusercontent.com/49781313/99115420-07a1df00-25fb-11eb-80f0-53c708798c51.png)

Если у записи нет уникального идентификатора, в качестве ключа можно использовать индекс итерации в сочетании с другими полями.

**Comment by aandrey1993** [comment]
В компоненте `SupportTable`, при прорисовки строк - ключ отсутствует:

![изображение](https://user-images.githubusercontent.com/49781313/99115664-7717ce80-25fb-11eb-995d-5fc658a8926d.png)

**Comment by aandrey1993** [comment]
Для форматирования данной даты, также можно использовать moment js:

![изображение](https://user-images.githubusercontent.com/49781313/99115778-a0385f00-25fb-11eb-9f2d-d05982ac0d56.png)

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/99143715-576abf80-2668-11eb-943d-e7a770545e1b.png)
![image](https://user-images.githubusercontent.com/58564568/99143865-afee8c80-2669-11eb-8620-9dc8c9c69ca1.png)
![image](https://user-images.githubusercontent.com/58564568/99143932-4a4ed000-266a-11eb-962c-5bd8ca481f79.png)
пофиксил спасибо
