### ISSUE TITLE
reduce complexity

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#3]
некоторые условия можно упростить: `data = data ? data : []  ->  data = data || []`

**Comment by maximburdiean** [comment]
что тут?

**Comment by Daimon31999** [comment]
тут сделал 
![image](https://user-images.githubusercontent.com/58564568/98974334-77419c80-251d-11eb-9c61-2d13a279ccc6.png)

**Comment by Daimon31999** [comment]
Исправил

чт, 12 нояб. 2020 г. в 18:49, Maxim A. Burdiean <notifications@github.com>:
