### ISSUE TITLE
simpler filters

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#4]
-  поиск на форме Support можно сделать в одном filter, чтобы 3 раза не перебирать массив и в целом условия можно сократить:
![image](https://user-images.githubusercontent.com/5040836/98919118-2313c980-24d7-11eb-983f-ca886a8d6347.png)

![image](https://user-images.githubusercontent.com/5040836/98919137-26a75080-24d7-11eb-8697-77f637b7198b.png)

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/98978238-592a6b00-2522-11eb-9ed9-45d7a564a3cb.png)
исправил
