### ISSUE TITLE
date twiddling strikes back

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#5]
-  На странице Support, дата вводится в обычном input. При вводе, дата опять же парсится как string и возникает ошибка при попытке считать результат split, если дата не заполнена полностью:

![image](https://user-images.githubusercontent.com/5040836/98919229-3c1c7a80-24d7-11eb-9dd8-f69a190406de.png)

Код парсинга даты:
![image](https://user-images.githubusercontent.com/5040836/98919250-4179c500-24d7-11eb-8f5b-fe2db44472af.png)

**Comment by Daimon31999** [comment]
эта проблема в кросс браузерности, к сожалению я разрабатывал в Chrome, и не протестировал как следует

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/98937112-a12f9a80-24ee-11eb-82dc-ba09b0c287be.png)
<TextField type="datetime-local"/> компонента от Material UI не работает с Firefox и Safari
