### ISSUE TITLE
search defaults and results display

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#6]
- Когда открывается форма Support, изначально страница пустая пока не нажать на кнопку. Также в раздел "Resultate cautare" всегда отображается имя первого пользователя списка, что не совсем правильно:

![image](https://user-images.githubusercontent.com/5040836/98919349-5bb3a300-24d7-11eb-83ff-13bbe4f2151b.png)

![image](https://user-images.githubusercontent.com/5040836/98919362-5f472a00-24d7-11eb-925b-0f0206c6ea5c.png)

**Comment by Daimon31999** [comment]
эта проблема в кросс браузерности, к сожалению я разрабатывал в Chrome, и не протестировал как следует

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/98945253-efe33180-24fa-11eb-805d-44582298282e.png)
исправленно
