### ISSUE TITLE
twiddling phone numbers too

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#7]
- Парсинг номера телефона, можно сделать регулярным выражением, либо настроить маску для ввода номера телефона, чтобы не учитывались спец символы вместо данного парсинга:

```
const handlePhoneChange = (value) => {
  value = value
    .split(' ')
    .join('')
    .split('(')
    .join('')
    .split(')')
    .join('')
    .split('-')
    .join('')
  if (value.length < 12) setPhone(null)
  else setPhone(value)
}
```

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/98942746-29b23900-24f7-11eb-8812-3949a5b3e266.png)
Исправленно

**Comment by aandrey1993** [comment]
В условии, длина строки проверяется с учетом символов самой маски, что не совсем правильно:

![изображение](https://user-images.githubusercontent.com/49781313/99116404-a2e78400-25fc-11eb-9eca-54d588fc1d4c.png)

Такой вариант ввода у меня не проходит:
![изображение](https://user-images.githubusercontent.com/49781313/99116511-d32f2280-25fc-11eb-87ae-9b80472dd4ea.png)

Если заполнить еще один символ, то проверку проходит и осуществляется поиск по номеру телефона (хотя он не заполнен до конца):
![изображение](https://user-images.githubusercontent.com/49781313/99116680-1db09f00-25fd-11eb-81a1-2e4b9f4f9eb8.png)
