### ISSUE TITLE
some more

### ISSUE THREAD

**Issue by maximburdiean** [Daimon31999/maib-task#9]
1. Данные для форм беруться из костант, без каких-либо timeout для эмуляции preloaders
2. Статика
![image](https://user-images.githubusercontent.com/5040836/98919626-b77e2c00-24d7-11eb-8504-e6eaf28474f8.png)
3. Выбор периода, никак не влияет на данные графика и таблице на странице Dashboard
4. Кнопка "Configura raport" ничего не делает. (просто заглушка)

**Comment by Daimon31999** [comment]
здесь я не до конца понял от куда брать данные для графика, поэтому просто создал файл data.js

**Comment by aandrey1993** [comment]
Добрый вечер. Меня зовут Андрей. Есть пару вопросов по поводу тестового задания.

На странице с графиком, при выборе периода, форма никак не реагирует. Меняется только label для графика.

Попробуйте сделать фильтрацию, на основе выбранного периода дат, для данных таблицы и желательно для данных самого графика.

![изображение](https://user-images.githubusercontent.com/49781313/99114707-e68cbe80-25f9-11eb-9a9b-1a5fea796459.png)

**Comment by Daimon31999** [comment]
Фильтрацию таблицы по периоду дат сделал
![image](https://user-images.githubusercontent.com/58564568/99154151-43e64580-26b6-11eb-949b-782032d68344.png)
![image](https://user-images.githubusercontent.com/58564568/99154142-3204a280-26b6-11eb-9043-10565ebadad5.png)
![image](https://user-images.githubusercontent.com/58564568/99154160-5ceef680-26b6-11eb-9e0d-e01b7a96ae21.png)
![image](https://user-images.githubusercontent.com/58564568/99154171-6f693000-26b6-11eb-9b79-625f37a946ab.png)

**Comment by Daimon31999** [comment]
Чтобы сделать фильтрацию для графика, я должен понять, что значит Page A, Page B ... , я не совсем понимаю что это

**Comment by Daimon31999** [comment]
Мне нужно это чтобы правильно построить структуру данных и понять логику фильтра

**Comment by aandrey1993** [comment]
Page A, Page B - это страницы приложения.  Данный график указывает сколько пользователей посетили страницу за определенный день. 

Попробуйте тут, для каждого объекта, добавить даты:

![изображение](https://user-images.githubusercontent.com/49781313/99233203-9b41fe00-27fb-11eb-8f30-fe400c9dffea.png)

По ним можно будет фильтровать страницы.

**Comment by Daimon31999** [comment]
## **Сделал фильтрацию для графика!**
![image](https://user-images.githubusercontent.com/58564568/99263388-c8a4a100-2827-11eb-949c-dd8b58b0fce1.png)

1. 
![image](https://user-images.githubusercontent.com/58564568/99263313-b0cd1d00-2827-11eb-8a51-4567b1afe106.png)
2. 
![image](https://user-images.githubusercontent.com/58564568/99263690-3781fa00-2828-11eb-8b8c-f58a5110e7fd.png)
3. 
![image](https://user-images.githubusercontent.com/58564568/99263743-4a94ca00-2828-11eb-8139-9df360ac2e57.png)

**Comment by Daimon31999** [comment]
Добавил динамику в этой карточке 
![image](https://user-images.githubusercontent.com/58564568/99273333-8e400180-2831-11eb-8e5f-d180b7dc57a2.png)

**Comment by aandrey1993** [comment]
По графику всё хорошо. По таблице тоже фильтрация работает, но логики фильтрации в render функции лучше избежать. Фильтрацию данных для таблицы можно вынести в компонент `Dashboard.jsx` и компоненту `MyTable` передавать готовый набор данных который необходимо вывести (по аналогии с данными для графика). Так образом получится избежать данных условий:

![изображение](https://user-images.githubusercontent.com/49781313/99283370-9bfb8400-283d-11eb-9cc9-9b5d5999def3.png)

Условие №2 также лучше вынести из map. Отдельно можно проверить, если переданный массив пустой, значит надо отобразить `No data`, иначе - запустить map и формировать строки таблицы на основе данных.

**Comment by Daimon31999** [comment]
![image](https://user-images.githubusercontent.com/58564568/99380934-44a7f300-28d3-11eb-848f-ab2db707fd35.png)

![image](https://user-images.githubusercontent.com/58564568/99380764-0c081980-28d3-11eb-9eee-d9f25032acd0.png)

Спасибо, исправил
